default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8mb4
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  timeout: 5000
  database: chew

development:
  <<: *default
  host: 127.0.0.1
  port: 3306

production:
  <<: *default
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port] %>
